### ISSUE TITLE
The page was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint HTTP. This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by taizooo** [taberareloo/taberareloo#285]
tumblr dashboard にて reblog 時エラーが出ており、reblog 出来ません。

![](http://i.gyazo.com/3ba225d4ad089a5f99e6119d0869b159.png)

以下は、  http://phantomoftheradio.tumblr.com/post/100116797179/sonideros の post を reblog した際の console でのエラーです。

```
Mixed Content: The page at 'https://www.tumblr.com/dashboard' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://phantomoftheradio.tumblr.com/post/100116797179/sonideros'. This request has been blocked; the content must be served over HTTPS.
```

実行環境は Taberareloo Canary 4.0.4.1 on Chrome dev 39.0.2171.7 m (64-bit) on windows になります。

**Comment by PaulSodimu** [comment]
Remove the protocol. http://www.paulsodimu.co.uk/Post/Quick-Tip-Using-Google-Fonts-Over-HTTPS

**Comment by housuchuan** [comment]
how to do?

**Comment by MtBoss** [comment]
this problem? who help me,SOS.
